package testplan

// Plan is a JSON test plan executed by tare-tool run-tests.
// It is generated by the orchestrator from a parsed YAML config.
type Plan struct {
	MetadataFile string `json:"metadataFile"`
	Tests        []Test `json:"tests"`
}

// TestType identifies which executor handles a test.
type TestType string

const (
	TypeMetadata      TestType = "metadata"
	TypeFileExistence TestType = "fileExistence"
	TypeFileContent   TestType = "fileContent"
	TypeScan          TestType = "scan"
	TypeCommand       TestType = "command"
)

// Test is a single test case in the plan. Exactly one of the
// type-specific fields will be populated, matching Type.
type Test struct {
	Name string   `json:"name"`
	Type TestType `json:"type"`

	Metadata      *MetadataSpec      `json:"metadata,omitempty"`
	FileExistence *FileExistenceSpec `json:"fileExistence,omitempty"`
	FileContent   *FileContentSpec   `json:"fileContent,omitempty"`
	Scan          *ScanSpec          `json:"scan,omitempty"`
	Command       *CommandSpec       `json:"command,omitempty"`
}

// MetadataSpec asserts one property of the container image configuration.
// Negate inverts the assertion ("must not be present").
type MetadataSpec struct {
	Field    string `json:"field"`              // "user", "workdir", "entrypoint", "cmd", "env", "label", "port", "volume"
	Key      string `json:"key,omitempty"`      // for env/label/port/volume: the identifier
	Expected string `json:"expected,omitempty"` // expected value (string or JSON array); unused when Negate
	IsRegex  bool   `json:"isRegex,omitempty"`
	Negate   bool   `json:"negate,omitempty"`
}

// FileExistenceSpec asserts existence and properties of a path. When
// ShouldExist is false, all other fields must be zero.
type FileExistenceSpec struct {
	Path            string   `json:"path"`
	ShouldExist     bool     `json:"shouldExist"`
	Type            string   `json:"type,omitempty"`    // "file", "dir", "symlink"
	NotType         string   `json:"notType,omitempty"` // path's type must not be this
	UID             *int     `json:"uid,omitempty"`
	GID             *int     `json:"gid,omitempty"`
	Permissions     string   `json:"permissions,omitempty"`
	ReadableBy      []string `json:"readableBy,omitempty"`
	NotReadableBy   []string `json:"notReadableBy,omitempty"`
	WritableBy      []string `json:"writableBy,omitempty"`
	NotWritableBy   []string `json:"notWritableBy,omitempty"`
	ExecutableBy    []string `json:"executableBy,omitempty"`
	NotExecutableBy []string `json:"notExecutableBy,omitempty"`
}

// FileContentSpec asserts file contents match or exclude patterns.
// Patterns are regular expressions; literal patterns are pre-escaped by
// the converter.
type FileContentSpec struct {
	Path             string   `json:"path"`
	ExpectedContents []string `json:"expectedContents,omitempty"`
	ExcludedContents []string `json:"excludedContents,omitempty"`
}

// ScanSpec configures ELF dependency scanning on a directory.
type ScanSpec struct {
	Path      string   `json:"path"`
	Ignore    []string `json:"ignore,omitempty"`
	Limit     int      `json:"limit,omitempty"`
	NoRuntime bool     `json:"noRuntime,omitempty"`
}

// CommandSpec runs a command and asserts on its output. Output patterns
// are regular expressions; literal patterns are pre-escaped by the converter.
type CommandSpec struct {
	Command        string     `json:"command"`
	Args           []string   `json:"args,omitempty"`
	Env            []KV       `json:"env,omitempty"`
	ExitCode       int        `json:"exitCode"`
	ExpectedOutput []string   `json:"expectedOutput,omitempty"`
	ExcludedOutput []string   `json:"excludedOutput,omitempty"`
	ExpectedError  []string   `json:"expectedError,omitempty"`
	ExcludedError  []string   `json:"excludedError,omitempty"`
	Setup          [][]string `json:"setup,omitempty"`
	Teardown       [][]string `json:"teardown,omitempty"`
}

// KV is a key/value pair carried over from the config to the plan.
type KV struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
